### ISSUE TITLE
Error: Cannot tap rubinius/apps: invalid syntax in tap!

### ISSUE THREAD

**Issue by douglasawh** [rubinius/homebrew-apps#10]
We've tried 10.13.6 (different error on 10.14.1)

A co-worker and I both get this following:

`==> Tapping rubinius/apps
Cloning into ‘/usr/local/Homebrew/Library/Taps/rubinius/homebrew-apps’...
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 20 (delta 14), reused 14 (delta 13), pack-reused 0
Unpacking objects: 100% (20/20), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/rubinius/homebrew-apps/rubinius-2.2.10.rb
rubinius-2.2.10: uninitialized constant #<Class:0x00000001022bb210>::MinimumMacOSRequirement
Did you mean?  MaximumMacOSRequirement
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/rubinius/homebrew-apps/rubinius-2.3.0.rb
rubinius-2.3.0: uninitialized constant #<Class:0x0000000102940950>::MinimumMacOSRequirement
Did you mean?  MaximumMacOSRequirement
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/rubinius/homebrew-apps/rubinius-2.4.0.rb
rubinius-2.4.0: uninitialized constant #<Class:0x00000001028b24c0>::MinimumMacOSRequirement
Did you mean?  MaximumMacOSRequirement
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/rubinius/homebrew-apps/rubinius-2.4.1.rb
rubinius-2.4.1: uninitialized constant #<Class:0x0000000102251d38>::MinimumMacOSRequirement
Did you mean?  MaximumMacOSRequirement
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/rubinius/homebrew-apps/rubinius-2.5.0.rb
rubinius-2.5.0: uninitialized constant #<Class:0x00000001021aa330>::MinimumMacOSRequirement
Did you mean?  MaximumMacOSRequirement
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/rubinius/homebrew-apps/rubinius-2.5.1.rb
rubinius-2.5.1: uninitialized constant #<Class:0x000000010204a5a8>::MinimumMacOSRequirement
Did you mean?  MaximumMacOSRequirement
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/rubinius/homebrew-apps/rubinius-2.5.2.rb
rubinius-2.5.2: uninitialized constant #<Class:0x0000000102c2ffa8>::MinimumMacOSRequirement
Did you mean?  MaximumMacOSRequirement
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/rubinius/homebrew-apps/rubinius-2.5.3.rb
rubinius-2.5.3: uninitialized constant #<Class:0x0000000102bc2db8>::MinimumMacOSRequirement
Did you mean?  MaximumMacOSRequirement
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/rubinius/homebrew-apps/rubinius-2.5.4.rb
rubinius-2.5.4: uninitialized constant #<Class:0x0000000102b5ddc8>::MinimumMacOSRequirement
Did you mean?  MaximumMacOSRequirement
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/rubinius/homebrew-apps/rubinius-2.5.5.rb
rubinius-2.5.5: uninitialized constant #<Class:0x0000000103051898>::MinimumMacOSRequirement
Did you mean?  MaximumMacOSRequirement
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/rubinius/homebrew-apps/rubinius-2.5.6.rb
rubinius-2.5.6: uninitialized constant #<Class:0x00000001024023a8>::MinimumMacOSRequirement
Did you mean?  MaximumMacOSRequirement
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/rubinius/homebrew-apps/rubinius-2.5.7.rb
rubinius-2.5.7: uninitialized constant #<Class:0x0000000102b05a10>::MinimumMacOSRequirement
Did you mean?  MaximumMacOSRequirement
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/rubinius/homebrew-apps/rubinius-2.5.8.rb
rubinius-2.5.8: uninitialized constant #<Class:0x0000000102a795d8>::MinimumMacOSRequirement
Error: Cannot tap rubinius/apps: invalid syntax in tap!`

**Comment by swrobel** [comment]
Still seeing this w/ latest homebrew/macOS @brixen:

```
$ brew tap rubinius/apps
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/cask-versions and homebrew/cask).
No changes to formulae.

==> Tapping rubinius/apps
Cloning into '/usr/local/Homebrew/Library/Taps/rubinius/homebrew-apps'...
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 20 (delta 14), reused 13 (delta 13), pack-reused 0
Unpacking objects: 100% (20/20), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/rubinius/homebrew-apps/rubinius-2.3.0.rb
rubinius-2.3.0: uninitialized constant #<Class:0x00007fac101ad5b0>::MinimumMacOSRequirement
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/rubinius/homebrew-apps/rubinius-2.5.0.rb
rubinius-2.5.0: uninitialized constant #<Class:0x00007fac109483d8>::MinimumMacOSRequirement
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/rubinius/homebrew-apps/rubinius-2.4.1.rb
rubinius-2.4.1: uninitialized constant #<Class:0x00007fac10941038>::MinimumMacOSRequirement
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/rubinius/homebrew-apps/rubinius-2.5.4.rb
rubinius-2.5.4: uninitialized constant #<Class:0x00007fac10932fb0>::MinimumMacOSRequirement
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/rubinius/homebrew-apps/rubinius.rb
rubinius: uninitialized constant #<Class:0x00007fac11b75f88>::MinimumMacOSRequirement
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/rubinius/homebrew-apps/rubinius-2.5.5.rb
rubinius-2.5.5: uninitialized constant #<Class:0x00007fac10996628>::MinimumMacOSRequirement
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/rubinius/homebrew-apps/rubinius-2.5.1.rb
rubinius-2.5.1: uninitialized constant #<Class:0x00007fac1099f070>::MinimumMacOSRequirement
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/rubinius/homebrew-apps/rubinius-2.4.0.rb
rubinius-2.4.0: uninitialized constant #<Class:0x00007fac109a7928>::MinimumMacOSRequirement
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/rubinius/homebrew-apps/rubinius-2.5.6.rb
rubinius-2.5.6: uninitialized constant #<Class:0x00007fac11242178>::MinimumMacOSRequirement
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/rubinius/homebrew-apps/rubinius-2.7.rb
rubinius-2.7: uninitialized constant #<Class:0x00007fac109ad6e8>::MinimumMacOSRequirement
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/rubinius/homebrew-apps/rubinius-2.5.2.rb
rubinius-2.5.2: uninitialized constant #<Class:0x00007fac109b5e60>::MinimumMacOSRequirement
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/rubinius/homebrew-apps/rubinius-2.5.3.rb
rubinius-2.5.3: uninitialized constant #<Class:0x00007fac109bdca0>::MinimumMacOSRequirement
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/rubinius/homebrew-apps/rubinius-2.5.7.rb
rubinius-2.5.7: uninitialized constant #<Class:0x00007fac11b7e430>::MinimumMacOSRequirement
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/rubinius/homebrew-apps/rubinius-2.2.10.rb
rubinius-2.2.10: uninitialized constant #<Class:0x00007fac11b87800>::MinimumMacOSRequirement
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/rubinius/homebrew-apps/rubinius-2.5.8.rb
rubinius-2.5.8: uninitialized constant #<Class:0x00007fac11218580>::MinimumMacOSRequirement
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/rubinius/homebrew-apps/rubinius-2.8.rb
rubinius-2.8: uninitialized constant #<Class:0x00007fac11b8c0f8>::MinimumMacOSRequirement
Error: Cannot tap rubinius/apps: invalid syntax in tap!
```

**Comment by michaeleisel** [comment]
Seeing this as well
